### ISSUE TITLE
Thank you for Your GREATTTTTTT WORK!

### ISSUE THREAD

**Issue by algolabs-kh** [rragundez/chunkdot#6]
Hey, I love this library and thank you for your efforts!

btw, I read that this awesome library supports GPU via Numba, but I could'n find.
(as far as I know, GPU acceleration with Numba works with decorator, is that right?)

Let me know if it already have updated.

Anyway, thank you for your work, I love your GREAT job!

**Comment by rragundez** [comment]
Hi @algolabs-kh  thanks a lot for your kind words. Numba does have support for GPUs with the use of decorators, this library, at this moment does not support GPUs though, I would need to make some changes in the source code. I was planning to take a look at this in a few weeks, is it really important for you to have this feature? Let me know your thoughts.

**Comment by algolabs-kh** [comment]
@rragundez Hi, I just wondered due to the words on your posting, April 5.
The ChunkDot is super enough for my projects (at least it is better than scikit-learn and faiss-included pipelines.)

AGAIN, I LOVE THIS PROJECT!

**Comment by rragundez** [comment]
Hi @algolabs-kh, do you have an example of how you used it as part of pipelines? 
I think it would be a nice addition to show that example of it would be used.

**Comment by rragundez** [comment]
Hi @algolabs-kh even if it is just a quick code snippet that will help for me to add some documentation about how to use it in the piles context. Thanks
